server:
  port: 8081

spring:
  application:
    name: order-service

  messages:
    basename: messages
    encoding: UTF-8

  datasource:
    url: jdbc:postgresql://localhost:5435/order_db
    username: order_user
    password: order_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: order-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html